library(dplyr)
PowerData <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
daterange <- c("1/2/2007", "2/2/2007")
PowerData <- filter(PowerData, Date %in% daterange)
MinutesElapsed <- data.frame(MinutesElapsed=1:2880)
PowerData <- cbind(PowerData, MinutesElapsed)
LabelList<-c("Thu","Fri","Sat")
png("plot3.png",width=480,height=480,units="px")
plot(PowerData$MinutesElapsed, PowerData$Sub_metering_1, type="n", ylab = "Energy sub metering", xaxt="n", xlab="")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_1, col = "black")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_2, col = "red")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"))
axis(side=1, at=c(1,1440,2880), labels=LabelList)
dev.off()

