library(dplyr)
PowerData <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
daterange <- c("1/2/2007", "2/2/2007")
PowerData <- filter(PowerData, Date %in% daterange)
PowerData$Global_active_power <- as.numeric(PowerData$Global_active_power)
png("plot1.png",width=480,height=480,units="px")
hist(PowerData$Global_active_power, main = "Global Active Power", col = "red", xlab = "Global Active Power (kilowatts)")
dev.off()