library(dplyr)
PowerData <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
daterange <- c("1/2/2007", "2/2/2007")
PowerData <- filter(PowerData, Date %in% daterange)
MinutesElapsed <- data.frame(MinutesElapsed=1:2880)
PowerData <- cbind(PowerData, MinutesElapsed)
LabelList<-c("Thu","Fri","Sat")
png("plot2.png",width=480,height=480,units="px")
plot(PowerData$MinutesElapsed, PowerData$Global_active_power, type="l", xlab = "", ylab = "Global Active Power (Kilowatts)", xaxt="n")
axis(side=1, at=c(1,1440,2880), labels=LabelList)
dev.off()