library(dplyr)
PowerData <- read.table("./household_power_consumption.txt", sep = ";", header = TRUE)
daterange <- c("1/2/2007", "2/2/2007")
PowerData <- filter(PowerData, Date %in% daterange)
MinutesElapsed <- data.frame(MinutesElapsed=1:2880)
PowerData <- cbind(PowerData, MinutesElapsed)
PowerData$Global_active_power <- as.numeric(PowerData$Global_active_power)
LabelList<-c("Thu","Fri","Sat")
png("plot4.png",width=480,height=480,units="px")
par(mfrow = c(2,2))
with(PowerData, {
plot(PowerData$MinutesElapsed, PowerData$Global_active_power, type="l", xlab = "", ylab = "Global Active Power", xaxt="n")
axis(side=1, at=c(1,1440,2880), labels=LabelList)

plot(PowerData$MinutesElapsed, PowerData$Voltage, type="l", xlab = "datetime", ylab = "Voltage", xaxt="n", yaxt="n")
axis(side=1, at=c(1,1440,2880), labels=LabelList)
axis(side=2, at=c(234, 236, 238, 240, 242, 244, 246), labels = c(234, "", 238, "", 242, "", 246))

plot(PowerData$MinutesElapsed, PowerData$Sub_metering_1, type="n", ylab = "Energy sub metering", xaxt="n", xlab="")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_1, col = "black")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_2, col = "red")
lines(PowerData$MinutesElapsed, PowerData$Sub_metering_3, col = "blue")
legend("topright", lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), bty="n")
axis(side=1, at=c(1,1440,2880), labels=LabelList)

plot(PowerData$MinutesElapsed, PowerData$Global_reactive_power, type="l", xlab = "datetime", ylab = "Global_reactive_power", xaxt="n", lwd = 0.5)
axis(side=1, at=c(1,1440,2880), labels=LabelList)
})
dev.off()